spring:
  datasource:
    url: jdbc:h2:file:./data/debts-tracker
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 4000
